### ISSUE TITLE
[FEATURE]: ikona pokazania hasła na ekranie logowania

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-frontend#106]
## Czy prośba o funkcję jest związana z problemem? Opisz go
Na ekranie logowania nie ma przycisku, który pokazywałby hasło
 
![image](https://github.com/user-attachments/assets/b670d34d-6bbb-40c6-a0c4-6219dd659f88)

**Comment by KubaBili001** [comment]
on it
