### ISSUE TITLE
[BUG]: Tryb ciemny jest słabo widoczny

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-frontend#107]
- [x] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
(temat był poruszany na spotkaniu ale robie issue dla porządku) Napisy i obiekty w trybie ciemnym są słabo widoczne

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. W prawym górnym rogu przełączamy na tryb ciemny
2. przechodzimy do ekranu zarządzania restauracją (ponieważ tam jest to najlepiej widoczne)

## Zrzuty ekranu
![image](https://github.com/user-attachments/assets/69eafa22-4347-45a1-bdcb-1dce221ca7f7)

**Comment by KubaBili001** [comment]
nooo, w ogole nie ma trybu ciemnego chwilowo xd

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dark theme](https://trello.com/c/jBOCPirt/88-dark-theme)
