### ISSUE TITLE
[BUG]: Zepsuty ekran dodawania restauracji

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-frontend#111]
- [x] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

![image](https://github.com/user-attachments/assets/1c6d2a75-8558-471b-bbdd-5dc87ecb33e2)

**Comment by KubaBili001** [comment]
To nie bug, po prostu jeszcze nie robilem wygladu, ale ogarne
