### ISSUE TITLE
[BUG]: Ekran restauracji

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-frontend#117]
Przy wejściu na ekran danej restauracji z poziomu restaurant management  
![image](https://github.com/user-attachments/assets/c7cb35bd-e831-4c9e-959a-41f11f8e9df4)

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Restaurant management screen error](https://trello.com/c/RwiNhoMm/83-restaurant-management-screen-error)

**Comment by KubaBili001** [comment]
Jest w trakcie na branchu Jarka

**Comment by JaroslawGawrych** [comment]
ale ja to już chyba skonczylem? na trello jest w review..
