### ISSUE TITLE
[BUG]: Błąd przy przejściu

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-frontend#122]
Na ekranie rejestracji użytkownika, po przejściu na drugi krok forma na pierwszym kroku zmienia swoją pozycję. (ciężko wytłumaczyć, jak coś to kontakt na dc).

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Register animation fix](https://trello.com/c/Wwu42wsS/89-register-animation-fix)

**Comment by JaroslawGawrych** [comment]
done imo
