### ISSUE TITLE
[BUG]: Błędy w formularzu tworzenia menu itema

### ISSUE THREAD

**Issue by linewelder** [Reservant-inc/reservant-frontend#144]
## Opisz błąd
- Alternate name jest zaznaczone jako wymagane
- Nie działa, bo nie podaje pól "photo" i "ingredients", a nie wyświetla błędu

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/615705c1-2710-4774-aa1e-4dab8bed988b)
![image](https://github.com/user-attachments/assets/bb870209-25f0-4985-b17d-0045aa0d5842)

**Comment by JaroslawGawrych** [comment]
pola ingredients i photo zostały dodane jako pola obowiązkowe.
pole alternate name jest polem opcjonalnym
