### ISSUE TITLE
Id przycisk do przejścia do detalu własnej restauracji powinno być niezależne od nazwy

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#164]
![obraz](https://github.com/user-attachments/assets/198cd39f-1d43-4cb5-a159-69b2b2b9082c)
aktualnie id dla restauracji np John Doe's to jest "RestaurantSeeDetailsButton0John" Doe's, najwygodniej żeby ten przycisk dla każdej restauracji miał takie same id np. "RestaurantSeeDetailsButton"

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by JaroslawGawrych** [comment]
to jakie chcecie id?

**Comment by JaroslawGawrych** [comment]
... pytam bo kiedyś było poruszone, żeby przyciski dotyczące rekordu w tabeli zwierały w html id jakiś jednoznaczny identyfikator rekordu. Obecnie jest to nazwa przycisku + id rekordu + nazwa rekordu, co spełnia ten warunek.

**Comment by Dzwiedzi** [comment]
Dobra wsm po dłuższym zastanowieniu może zostać. XDD
