### ISSUE TITLE
[BUG]: Rezerwacje

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#165]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
-Brak rozróżnienia gości od uczestników
-Rezerwacja się nie dodaje(błąd widoczny w ss)

## Oczekiwane zachowanie
-Rozróżnienie gości od uczestników
-Pomyślne dodanie rezerwacji

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/3f0ad554-8f98-410e-8ccf-555b0104631a)

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by JaroslawGawrych** [comment]
On it. How is that management related issue tho?
