### ISSUE TITLE
[BUG]: Zamówienia

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#166]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
-Produkty nie dodają się do koszyka
-skip order nic nie robi

## Oczekiwane zachowanie
-Produkty będą dodawały się do koszyka
-skip order będzie funkcjonalny

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/56627d03-ef2e-4cc7-8ea3-d333018c1ac1)

## Dodatkowy kontekst (opcjonalnie)
Dodatkowo myślę że nie powinniśmy tutaj wyświetlać pustych menu

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)
