### ISSUE TITLE
[BUG]: Edytowanie pracownika

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#167]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Edycja pracownika nie wysyła żądania do backendu o zapisanie danych

## Oczekiwane zachowanie
Zapisanie zmian w backendzie

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/d620f88b-6002-40fd-942c-a2d633482713)

**Comment by Dzwiedzi** [comment]
Jednak duplikat

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)
