### ISSUE TITLE
[BUG]: Usuwanie pracownika

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#168]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Usunięcie pracownika przenosi nas na czystą stronę i nie usuwa pracownika

## Oczekiwane zachowanie
Pracownik zostaje usunięty w backendzie i dostajemy informację że pracownik został usunięty

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/a81e87b1-9031-4fd4-900c-ec719073e3df)

**Comment by Dzwiedzi** [comment]
Jednak duplikat

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)
