### ISSUE TITLE
[BUG]: Przypisywanie zatrudnienia

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#169]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Przypisywanie zatrudnienia powinno być z pozycji wszystkich pracowników a nie jak już jest dodany do restauracji, bo teraz jak dodamy nowego pracownika dla właściciela to nie mamy jak przypisać do do restauracji bo przycisk przypisywania jest dostępny dopiero dla przypisanych pracowników

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/135256a4-3a97-4369-8a0c-d76880fd32bb)

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by JaroslawGawrych** [comment]
podobnie jak w innym issue, problem już rozwiązany i czeka na merge
