### ISSUE TITLE
[BUG]: Dodanie MenuItemu z poziomu edycji menu

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#170]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Nie możemy dodać MenuItemu z poziomu edycji menu bo zmiany się nie zapiszą

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/630db6aa-3e26-4ce4-940d-a9012bfbd42b)

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by JaroslawGawrych** [comment]
podobnie jak z dwoma innymi issues, problem już rozwiązany, czeka na merge.
