### ISSUE TITLE
[BUG]: ID jest identyczne dla wszystkich pracowników restauracji

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-frontend#175]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
Dla właściciela restauracji (JD), w panelu do zarządzania pracownikami "Employee management", ID dla wszystkich pracowników są takie same 

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Zaloguj się jako JD
2. Przejdź do panelu Zarządzania
3. Wybierz zakładkę "Employee Management"
4. Rozciągnij kolumnę ID (żeby zobaczyć cały ciąg znaków ID)
5. Zobacz błąd

## Oczekiwane zachowanie
ID powinno być unikalne dla każdego pracownika

## Zrzuty ekranu (opcjonalnie)
<img width="728" alt="Zrzut ekranu 2024-10-30 182208" src="https://github.com/user-attachments/assets/f983b45c-dca2-46c5-b170-b4bf62dfcc18">

**Comment by KubaBili001** [comment]
Note to Jarek - id do wywalenia z tej tabeli

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by KubaBili001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Management related issues](https://trello.com/c/e1NHUSKy/113-management-related-issues)

**Comment by JaroslawGawrych** [comment]
to już zostało naprawione
issue było, jest już zamknięte
id nie ma w tej tabeli 
prośba do zespołu testów o nie podkradanie pomysłów na problemy, pozdrawiam
