### ISSUE TITLE
[BUG]: Ucinanie przycisków przy rejestracji

### ISSUE THREAD

**Issue by AdrianSwdr** [Reservant-inc/reservant-frontend#218]
- [ ] **__Sprawdziłem i nikt nie zgłosił takiego błędu na issues__**

## Opisz błąd
Przy wpisaniu samych złych danych przy rejestracji ucina przyciski

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Wpisz wszędzie złe dane

## Oczekiwane zachowanie
Ucina przyciski

## Zrzuty ekranu (opcjonalnie)
![issue](https://github.com/user-attachments/assets/a6a612cd-0124-472f-8eb9-90cfb61c6482)

**Comment by JaroslawGawrych** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG]: Ucinanie przycisków przy rejestracji #218](https://trello.com/c/m1gbE76j/143-bug-ucinanie-przycisk%C3%B3w-przy-rejestracji-218)
