### ISSUE TITLE
[BUG] home route redirect bug

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-frontend#32]
Wejście na [172.21.40.127/home](http://172.21.40.127/home) gdy nie jesteśmy zalogowani przekierowuje nas na stronę logowania ale wygląda jakby błędnie się ładowała
![image](https://github.com/Reservant-inc/reservant-frontend/assets/50219282/6e8a3ce2-a67b-4d84-8cef-473eba09d204)

**Comment by KubaBili001** [comment]
to jest easy fix, po prostu jesy auth zamiast user w url, zara zmienie
