### ISSUE TITLE
Polskie znaki

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-frontend#62]
Formularz rejestracji użytkownika nie dopuszcza polskich znaków w polach 'Imię' i 'Nazwisko', natomiast dopuszcza polskie znaki w polu 'login'

**Comment by JaroslawGawrych** [comment]
dodano dopuszczalne znaki: ą ć ę ł ń ó ś ź ż Ą Ć Ę Ł Ń Ó Ś Ź Ż
