### ISSUE TITLE
Dodać ID w klikalnych komponentach na rzecz testów

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-frontend#83]
Na rzecz testów potrzebujemy w komponentach (głównie w tych, co się powtarzają) unikalne ID w celu identyfikacji tego komponentu, jak w przypadku poniżej:

![image](https://github.com/Reservant-inc/reservant-frontend/assets/91696484/388e023e-cb59-4300-a21d-36dde3bb94d5)

**Comment by JaroslawGawrych** [comment]
poszła zmiana
